### ISSUE TITLE
Candles do not use the modified flame texture in 1.21.1 - 1.21.3

### ISSUE THREAD

**Issue by Enchi-Man** [Tschipcraft/better_flame_particles#1]
### Describe the bug

Candles use the vanilla flame particle rather than the animated one from the resource pack

**Comment by Tschipcraft** [comment]
![Works on my machine](https://github.com/user-attachments/assets/37df05ea-5441-418d-9824-a2529987d9fe)

I cannot reproduce this, do you have any other resource packs/mods installed? If so, please attach your most recent log (e.g. using [mclo.gs](https://mclo.gs/))

**Comment by Enchi-Man** [comment]
Sure.
This screenshot was taken in 1.21.3, with no mods, and only this resource pack enabled, the torch is working as intended, but the candle is not.
![2024-10-29_22 49 03](https://github.com/user-attachments/assets/fb39b26d-c636-4dc2-923e-823eb8ff2234)

**Comment by Tschipcraft** [comment]
Oh, my mistake. I didn't notice you wrote candles. I will look into this

**Comment by Tschipcraft** [comment]
Fixed in v2.2 :tada:
